name: Build

on:
  push:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - uses: actions/cache@v4
        with:
          path: ~/.ghcup
          key: ghcup-${{ runner.os }}-9.10.3

      - uses: haskell-actions/setup@v2
        with:
          ghc-version: 9.10.3
          enable-stack: true

      - uses: actions/cache@v4
        with:
          path: |
            ~/.stack
            .stack-work
          key: stack-${{ runner.os }}-${{ hashFiles('stack.yaml.lock', 'effectful-monad-logger.cabal') }}
          restore-keys: stack-${{ runner.os }}-

      - run: stack --system-ghc --no-install-ghc build --test --only-dependencies

      - run: stack --system-ghc --no-install-ghc test
